# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 16:41
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_service_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='preview_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
            preserve_default=False,
        ),
    ]
