# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_service_preview_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_set_crop',
            field=image_cropping.fields.ImageRatioField('image', '470x526', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='\u041e\u0431\u0440\u0435\u0437\u043a\u0430 \u0434\u043b\u044f \u0443\u0441\u043b\u0443\u0433\u0438 470x526'),
        ),
        migrations.AlterField(
            model_name='service',
            name='preview_text',
            field=models.TextField(verbose_name='\u041f\u0440\u0435\u0432\u044c\u044e'),
        ),
    ]
