# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20160504_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='recent_posts',
            field=models.ManyToManyField(blank=True, to='core.Post'),
        ),
    ]
