# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20160504_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_text',
            field=models.TextField(default='', verbose_name='\u041f\u0440\u0435\u0432\u044c\u044e'),
            preserve_default=False,
        ),
    ]
