# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20160504_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='published',
            field=models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u0442\u044c \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b'),
        ),
    ]
