# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0015_project_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='is_plan',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043b\u0430\u043d'),
        ),
    ]
