# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 14:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0016_projectimage_is_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='material',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
