# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0017_project_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='address',
        ),
        migrations.AddField(
            model_name='project',
            name='dimensions_home',
            field=models.CharField(default='18.24x10.24m', max_length=100, verbose_name='\u0413\u0430\u0431\u0430\u0440\u0438\u0442\u044b \u0434\u043e\u043c\u0430'),
            preserve_default=False,
        ),
    ]
