# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0018_auto_20160504_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='building_area',
            field=models.IntegerField(default=12, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c \u0437\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438'),
            preserve_default=False,
        ),
    ]
