# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0020_auto_20160504_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sku',
        ),
    ]
