# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0021_remove_project_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='combined_area',
            field=models.IntegerField(default=100, verbose_name='\u041e\u0431\u0449\u0430\u044f \u043f\u043b\u043e\u0449\u0430\u0434\u044c'),
            preserve_default=False,
        ),
    ]
