# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0023_auto_20160504_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='building_area',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c \u0437\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='project',
            name='combined_area',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u041e\u0431\u0449\u0430\u044f \u043f\u043b\u043e\u0449\u0430\u0434\u044c'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ridge_height',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u0413\u0430\u0431\u0430\u0440\u0438\u0442\u044b \u0434\u043e\u043c\u0430'),
        ),
        migrations.AlterField(
            model_name='project',
            name='roof_area',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c \u043a\u0440\u044b\u0448\u0438'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ugol_inclination',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u0423\u0433\u043e\u043b \u043d\u0430\u043a\u043b\u043e\u043d\u0430 \u043a\u0440\u044b\u0448\u0438'),
        ),
    ]
