# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0025_remove_project_ridge_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='badrooms',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bathrooms',
        ),
    ]
