# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0028_auto_20160504_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='garage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='siteprojects.Garage', verbose_name='\u0413\u0430\u0440\u0430\u0436'),
            preserve_default=False,
        ),
    ]
