# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0032_auto_20161003_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='building_area',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c \u0437\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438'),
        ),
    ]
