# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0033_auto_20161003_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='building_area',
            field=models.CharField(default='', max_length=100, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c \u0437\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438'),
            preserve_default=False,
        ),
    ]
